### ISSUE TITLE
Lab1-2

### ISSUE THREAD

**Issue by AlekseiMaslakov** [BesedinDaniil/TasksForTheUniversity#1]
Здравствуйте

Lab1.A - ok
Lab1.B - ok
Lab1.C - команды вывода и поиска вижу, а где всё остальное?)

Lab2.A - ok
Lab2.B - ok

**Comment by BesedinDaniil** [comment]
Прочитав задание, подумал, что там говорится про урезанный функционал CRUD, который реализует только эти операции.

**Comment by AlekseiMaslakov** [comment]
Но реализованные операции не входят в CRUD, как они могут быть его урезанным функционалом?

**Comment by BesedinDaniil** [comment]
К read нельзя это приравнять?

**Comment by BesedinDaniil** [comment]
Не разобрался, в среду исправлю.

**Comment by BesedinDaniil** [comment]
Задание 1с исправлено.

**Comment by BesedinDaniil** [comment]
Только операцию read не стал добавлять, т к все еще считаю, что она уже была реализована в (print & search and print).
